# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: cmorgan2019/pod-test:0.4

clone:
  lfs: true

pipelines:
  default:
    - parallel:
        - step:
            name: Run Example 1
            script:
              - pwd
              - ls
              - mkdir -p /data
              - mkdir -p /data/acs
              - mkdir -p /data/acs/pod
              - cp -R /opt/atlassian/pipelines/agent/build/* /data/acs/pod/
              - ln -s /data/acs/pod/ /root/home/pod
              - cd /data/acs/pod
              - mkdir build
              - cd build
              - cmake ..
              - make >make.out 2>make.err
              - less make.err
              - python3 ../scripts/install_examples.py
              - cd ../examples/ex1
              - find -type l -delete
              - chmod +x sh_ex1
              - ./sh_ex1
              - cat pod.out
              - cat pod.rms
              - python3 test.py
        - step:
            name: Run Example 2
            script:
              - ln -s /opt/atlassian/pipelines/agent/build /data/acs/pod
              - mkdir -p /data
              - mkdir -p /data/acs
              - cd /data/acs/pod
              - ls
              - mkdir build
              - cd build
              - cmake ..
              - make >make.out 2>make.err
              - less make.err
              - python3 ../scripts/install_examples.py
              - cd ../examples/ex2
              - find -type l -delete
              - ./sh_ex2
              - cat pod.out
              - cat pod.rms
              - python3 test.py
        - step:
            name: Run Example 3
            script:
              - mkdir /root/pod
              - cp -r * /root/pod
              - cd /root/pod
              - mkdir build
              - cd build
              - cmake ..
              - make >make.out 2>make.err
              - less make.err
              - python3 ../scripts/install_examples.py
              - cd ../examples/ex3
              - find -type l -delete
              - ./sh_ex3
              - cat pod.out
              - cat pod.rms
              - python3 test.py
        - step:
            name: Run Example 4
            script:
              - mkdir /root/pod
              - cp -r * /root/pod
              - cd /root/pod
              - mkdir build
              - cd build
              - cmake ..
              - make >make.out 2>make.err
              - less make.err
              - python3 ../scripts/install_examples.py
              - cd ../examples/ex4
              - find -type l -delete
              - ./sh_ex4
              - cat pod.out
              - cat pod.rms
              - python3 test.py
