# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: cmorgan2019/pod-test:0.4

clone:
  lfs: true

pipelines:
  default:
    - parallel:
        - step:
            name: Run Example 1
            script:
              - ln -s /opt/atlassian/pipelines/agent/build /root/pod
              - mkdir -p /data/acs/pod
              - mkdir build
              - cd build
              - cmake ..
              - make >make.out 2>make.err
              - less make.err
              - python3 ../scripts/download_examples.py
              - cd /data/acs/pod/ex1
              - find -type l -delete
              - ln -s /data/acs/pod/tables/ascp1950.430 .             >& /dev/null
              - ln -s /data/acs/pod/tables/fes2004_Cnm-Snm.dat .      >& /dev/null
              - ln -s /data/acs/pod/tables/goco05s.gfc .              >& /dev/null
              - ln -s /data/acs/pod/tables/header.430_229 .           >& /dev/null
              - ln -s /data/acs/pod/tables/igs_metadata_2063.snx .    >& /dev/null
              - ln -s /data/acs/pod/tables/leap.second .              >& /dev/null
              - ln -s /data/acs/pod/tables/eopc04_14_IAU2000.62-now . >& /dev/null
              - python3 /root/pod/scripts/update_tables.py
              - ~/pod/bin/pod | tee pod.out
              - python3 ~/pod/scripts/res_plot.py     -i gag19424_igs19424_orbdiff_rtn.out -d . -c G >& /dev/null
              - python3 ~/pod/scripts/rms_bar_plot_bitbucket.py -i gag19424_igs19424_orbdiff_rtn.out -d . -c G >& pod.rms
              - cp /root/pod/scripts/compare_pod_rms.py .
              - python3 compare_pod_rms.py
        - step:
            name: Run Example 2
            script:
              - ln -s /opt/atlassian/pipelines/agent/build /root/pod
              - mkdir build
              - cd build
              - cmake ..
              - make >make.out 2>make.err
              - less make.err
              - mkdir -p /data/acs/pod
              - python3 ../scripts/download_examples.py
              - cd /data/acs/pod/ex2
              - find -type l -delete
              - ln -s /data/acs/pod/tables/ascp1950.430 .             >& /dev/null
              - ln -s /data/acs/pod/tables/fes2004_Cnm-Snm.dat .      >& /dev/null
              - ln -s /data/acs/pod/tables/goco05s.gfc .              >& /dev/null
              - ln -s /data/acs/pod/tables/header.430_229 .           >& /dev/null
              - ln -s /data/acs/pod/tables/igs_metadata_2063.snx .    >& /dev/null
              - ln -s /data/acs/pod/tables/leap.second .              >& /dev/null
              - ln -s /data/acs/pod/tables/eopc04_14_IAU2000.62-now . >& /dev/null
              - python3 /root/pod/scripts/update_tables.py
              - ~/pod/bin/pod | tee pod.out
              - python3 ~/pod/scripts/res_plot.py     -i gag20624__orbdiff_rtn.out -d . -c C >& /dev/null
              - python3 ~/pod/scripts/res_plot.py     -i gag20624__orbdiff_rtn.out -d . -c E >& /dev/null
              - python3 ~/pod/scripts/res_plot.py     -i gag20624__orbdiff_rtn.out -d . -c G >& /dev/null
              - python3 ~/pod/scripts/res_plot.py     -i gag20624__orbdiff_rtn.out -d . -c R >& /dev/null
              - python3 ~/pod/scripts/rms_bar_plot_bitbucket.py -i gag20624__orbdiff_rtn.out -d . -c C >& pod_C.rms
              - python3 ~/pod/scripts/rms_bar_plot_bitbucket.py -i gag20624__orbdiff_rtn.out -d . -c E >& pod_E.rms
              - python3 ~/pod/scripts/rms_bar_plot_bitbucket.py -i gag20624__orbdiff_rtn.out -d . -c G >& pod_G.rms
              - python3 ~/pod/scripts/rms_bar_plot_bitbucket.py -i gag20624__orbdiff_rtn.out -d . -c R >& pod_R.rms
              - cp /root/pod/scripts/compare_pod_rms.py .
              - python3 compare_pod_rms.py -sr pod_C.rms -rr pod_C.rms -so pod.out -ro pod.out --errormargin 0.5
              - python3 compare_pod_rms.py -sr pod_E.rms -rr pod_E.rms -so pod.out -ro pod.out --errormargin 0.5
              - python3 compare_pod_rms.py -sr pod_G.rms -rr pod_G.rms -so pod.out -ro pod.out --errormargin 0.5
              - python3 compare_pod_rms.py -sr pod_R.rms -rr pod_R.rms -so pod.out -ro pod.out --errormargin 0.5
        - step:
            name: Run Example 3
            script:
              - ln -s /opt/atlassian/pipelines/agent/build /root/pod
              - mkdir build
              - cd build
              - cmake ..
              - make >make.out 2>make.err
              - less make.err
              - mkdir -p /data/acs/pod
              - python3 ../scripts/download_examples.py
              - cd /data/acs/pod/ex3
              - find -type l -delete
              - ln -s /data/acs/pod/tables/ascp1950.430 .             >& /dev/null
              - ln -s /data/acs/pod/tables/fes2004_Cnm-Snm.dat .      >& /dev/null
              - ln -s /data/acs/pod/tables/goco05s.gfc .              >& /dev/null
              - ln -s /data/acs/pod/tables/header.430_229 .           >& /dev/null
              - ln -s /data/acs/pod/tables/igs_metadata_2063.snx .    >& /dev/null
              - ln -s /data/acs/pod/tables/leap.second .              >& /dev/null
              - ln -s /data/acs/pod/tables/eopc04_14_IAU2000.62-now . >& /dev/null
              - python3 /root/pod/scripts/update_tables.py
              - ~/pod/bin/pod | tee pod.out
              - python3 ~/pod/scripts/res_plot.py     -i gag20010_igs20010_orbdiff_rtn.out -d . -c G >& /dev/null
              - python3 ~/pod/scripts/rms_bar_plot_bitbucket.py -i gag20010_igs20010_orbdiff_rtn.out -d . -c G >& pod.rms
              - cp /root/pod/scripts/compare_pod_rms.py .
              - python3 compare_pod_rms.py --errormargin 0.5
        - step:
            name: Run Example 4
            script:
              - ln -s /opt/atlassian/pipelines/agent/build /root/pod
              - mkdir build
              - cd build
              - cmake ..
              - make >make.out 2>make.err
              - less make.err
              - mkdir -p /data/acs/pod
              - python3 ../scripts/download_examples.py
              - cd /data/acs/pod/ex4
              - find -type l -delete
              - ln -s /data/acs/pod/tables/ascp1950.430 .             >& /dev/null
              - ln -s /data/acs/pod/tables/fes2004_Cnm-Snm.dat .      >& /dev/null
              - ln -s /data/acs/pod/tables/goco05s.gfc .              >& /dev/null
              - ln -s /data/acs/pod/tables/header.430_229 .           >& /dev/null
              - ln -s /data/acs/pod/tables/igs_metadata_2063.snx .    >& /dev/null
              - ln -s /data/acs/pod/tables/leap.second .              >& /dev/null
              - ln -s /data/acs/pod/tables/eopc04_IAU2000.62-now . >& /dev/null
              - cd /data/acs/pod/tables/
              - ls
              - cd /data/acs/pod/ex4
              - python3 /root/pod/scripts/update_tables.py
              - ~/pod/bin/pod -r eopc04_IAU2000.62-now | tee pod.out
              - python3 ~/pod/scripts/res_plot.py     -i gag20624_igs20624_orbdiff_rtn.out -d . -c G >& /dev/null
              - python3 ~/pod/scripts/rms_bar_plot_bitbucket.py -i gag20624_igs20624_orbdiff_rtn.out -d . -c G >& pod.rms
              - cp /root/pod/scripts/compare_pod_rms.py .
              - python3 compare_pod_rms.py --errormargin 0.5
